apiVersion: apps/v1
kind: Deployment
metadata:
  name: commandfail-fail
  labels:
    app: failing-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: failing-app
      component: commandfail-fail
  template:
    metadata:
      labels:
        app: failing-app
        component: commandfail-fail
    spec:
      containers:
      - name: test-container
        image: busybox
        command:
        - /bin/sh
        - -c
        - echo 'Container failing...'; exit 1
