apiVersion: apps/v1
kind: Deployment
metadata:
  name: failing-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: failing-app
  template:
    metadata:
      labels:
        app: failing-app
    spec:
      containers:
      - name: crash
        image: busybox
        command:
        - /bin/sh
        - -c
        - while true; do echo 'Container running...'; sleep 60; done
