apiVersion: apps/v1
kind: Deployment
metadata:
  name: imagepullbackoff-fail
  labels:
    app: failing-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: failing-app
      component: imagepullbackoff-fail
  template:
    metadata:
      labels:
        app: failing-app
        component: imagepullbackoff-fail
    spec:
      containers:
      - name: test-container
        image:
          newRepository: your-new-repository-url.com
          newTag: your-new-tag-name
